version: '3.8'
services:
  algorithm-repo:
    build: ./backend
    container_name: algorithm_repository_debug
    ports:
      - 55955:55955
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./backend
    container_name: algorithm_repository_worker
    command: celery --app=src.worker.celery worker --loglevel=INFO
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - algorithm-repo
      - redis

#  dashboard:
#    build: ./backend
#    container_name: algorithm_repository_dashboard
#    command: celery flower --app==src.worker.celery --port=5555 --broker=redis://redis:6379/0
#    ports:
#      - 5555:5555
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - CELERY_RESULT_BACKEND=redis://redis:6379/0
#    depends_on:
#      - worker

  redis:
    image: redis:7-alpine